global:
  scrape_interval: 10s

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - custom-nginx-exporter:9113
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.* # Drop all metrics starting with "go_"
        action: drop
